line_length:
  - 300 # warning
  - 400 # error

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - eggs/Library

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_cast
  - identifier_name
